@base-url = http://localhost:8080
@hello = {{base-url}}/hello
@medics = {{base-url}}/medics
@patients = {{base-url}}/patients
@auth = {{base-url}}/auth
@users = {{base-url}}/users
@appointments = {{base-url}}/appointments

@token = <token>

###
POST {{auth}} HTTP/1.1
Content-Type: application/json

{
    "login":"admin",
    "password":"root"
}

# {
#     "login":"new_user",
#     "password":"123"
# }

###
POST {{users}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "login":"another_user",
    "password":"123",
    "profile":"ROLE_ADMIN"
}

###
GET {{users}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{users}}/3 HTTP/1.1
Authorization: Bearer {{token}}

###
DELETE  {{users}}/2 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{hello}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{medics}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{medics}}/1
Authorization: Bearer {{token}}

###
DELETE {{medics}}/4
Authorization: Bearer {{token}}

###
POST {{medics}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Dr. Silva",
    "telephone": "28414192",
    "register": "35253",
    "email":"doctor5@email.com",
    "field": "ORTHOPEDICS",
    "address": {
        "street": "Main street",
        "zip": "01247641",
        "city": "Metropolis",
        "state": "AB",
        "number": "123"
    }
}

###
PUT {{medics}}
Content-Type: application/json

{
    "id": 7,
    "name": "Dr. Silva",
    "email": "silva23@hotmail.com",
    "telephone": "28414192",
    "register": "2349",
    "field": "ORTHOPEDICS",
    "address": {
        "street": "Rua da mata novo end",
        "zip": "01247641",
        "city": "Vilopolis",
        "state": "AB",
        "number":"123"
    }
}

###
GET {{appointments}} HTTP/1.1
Authorization: Bearer {{token}}
###

GET {{appointments}}/1 HTTP/1.1
Authorization: Bearer {{token}}
###

POST {{appointments}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "medicId":1,
    "patientId":1,
    "date":"2023-08-16T10:22:11"
}

###
GET {{patients}} HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{patients}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Patient 2",
    "email": "patient2@email.com",
    "telephone":"29323421",
    "ssn":"47132047013",
    "address": {
        "street":"Street 2",
        "zip":"60139457",
        "city":"Metropolie",
        "state":"CC",
        "number":"123"
    }
}

###
DELETE {{patients}}/2 HTTP/1.1
Authorization: Bearer {{token}}
